-- ============================================================
-- JUAMPYZEL - SCHEMA SUPABASE (PostgreSQL)
-- ============================================================
-- Este script reemplaza el esquema anterior de MySQL/Workbench.
-- Ejecutar una sola vez en el SQL Editor de Supabase
-- (o mediante: supabase db push / psql).
--
-- Incluye:
--   * Tablas (con sus constraints e indices)
--   * Datos semilla (usuarios y categorias iniciales)
--   * Vistas para consultas con agregaciones
--   * Funciones (RPC) para operaciones atomicas y reportes
--   * Row Level Security (RLS)
--
-- NOTA: El backend accede con la clave SERVICE ROLE (que ignora
-- RLS por diseno). Las politicas RLS protegen el acceso directo
-- con la publishable/anon key. No se crean politicas publicas
-- de escritura (USING true) porque romperian la seguridad.
-- ============================================================


-- ============================================================
-- 1. USUARIO
-- ============================================================

CREATE TABLE public.usuario (
    id_usuario        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre            VARCHAR(100) NOT NULL,
    apellido          VARCHAR(100) NOT NULL,
    correo            VARCHAR(150) NOT NULL,
    password          VARCHAR(255) NOT NULL,
    rol               VARCHAR(20)  NOT NULL DEFAULT 'VENDEDOR',
    estado            BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_registro    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_correo UNIQUE (correo),
    CONSTRAINT chk_usuario_nombre CHECK (CHAR_LENGTH(BTRIM(nombre)) >= 2),
    CONSTRAINT chk_usuario_apellido CHECK (CHAR_LENGTH(BTRIM(apellido)) >= 2),
    CONSTRAINT chk_usuario_rol CHECK (rol IN (
        'ADMINISTRADOR', 'ENCARGADO_SUCURSAL', 'VENDEDOR', 'INVENTARIO', 'TIENDA'
    ))
);

-- ============================================================
-- 2. CATEGORIA
-- ============================================================

CREATE TABLE public.categoria (
    id_categoria   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre         VARCHAR(100) NOT NULL,
    descripcion    VARCHAR(200),
    estado         BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_categoria PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoria_nombre UNIQUE (nombre),
    CONSTRAINT chk_categoria_nombre CHECK (CHAR_LENGTH(BTRIM(nombre)) >= 2)
);

-- ============================================================
-- 3. PRODUCTO
-- ============================================================

CREATE TABLE public.producto (
    id_producto    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_categoria   BIGINT NOT NULL,
    nombre         VARCHAR(150) NOT NULL,
    descripcion    TEXT,
    precio         NUMERIC(10,2) NOT NULL,
    stock_minimo   BIGINT NOT NULL DEFAULT 5,
    imagen         VARCHAR(255),
    estado         BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_producto PRIMARY KEY (id_producto),
    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (id_categoria) REFERENCES public.categoria(id_categoria)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_producto_precio CHECK (precio > 0),
    CONSTRAINT chk_producto_stock_minimo CHECK (stock_minimo >= 0)
);

CREATE INDEX idx_producto_categoria ON public.producto(id_categoria);
CREATE INDEX idx_producto_nombre ON public.producto(nombre);
CREATE INDEX idx_producto_estado ON public.producto(estado);

-- ============================================================
-- 4. SUCURSAL
-- ============================================================

CREATE TABLE public.sucursal (
    id_sucursal      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre           VARCHAR(100) NOT NULL,
    direccion        VARCHAR(200) NOT NULL,
    telefono         VARCHAR(20),
    id_responsable   BIGINT,
    estado           BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_sucursal PRIMARY KEY (id_sucursal),
    CONSTRAINT fk_sucursal_responsable
        FOREIGN KEY (id_responsable) REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT uq_sucursal_nombre UNIQUE (nombre),
    -- Un encargado de sucursal solo puede estar a cargo de una sucursal.
    CONSTRAINT uq_sucursal_responsable UNIQUE (id_responsable),
    CONSTRAINT chk_sucursal_nombre CHECK (CHAR_LENGTH(BTRIM(nombre)) >= 2),
    CONSTRAINT chk_sucursal_direccion CHECK (CHAR_LENGTH(BTRIM(direccion)) >= 5)
);

-- ============================================================
-- 5. CLIENTE
-- ============================================================

CREATE TABLE public.cliente (
    id_cliente       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario       BIGINT,
    nombres          VARCHAR(100) NOT NULL,
    apellidos        VARCHAR(100) NOT NULL,
    telefono         VARCHAR(20),
    correo           VARCHAR(150),
    direccion        VARCHAR(200),
    fecha_registro   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT fk_cliente_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT uq_cliente_usuario UNIQUE (id_usuario),
    CONSTRAINT uq_cliente_correo UNIQUE (correo),
    CONSTRAINT chk_cliente_nombres CHECK (CHAR_LENGTH(BTRIM(nombres)) >= 2),
    CONSTRAINT chk_cliente_apellidos CHECK (CHAR_LENGTH(BTRIM(apellidos)) >= 2)
);

CREATE INDEX idx_cliente_nombres ON public.cliente(nombres);
CREATE INDEX idx_cliente_apellidos ON public.cliente(apellidos);

-- ============================================================
-- 6. TIENDA
-- ============================================================

CREATE TABLE public.tienda (
    id_tienda        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario       BIGINT,
    nombre           VARCHAR(150) NOT NULL,
    responsable      VARCHAR(100) NOT NULL,
    telefono         VARCHAR(20),
    correo           VARCHAR(150),
    direccion        VARCHAR(200) NOT NULL,
    estado           BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_tienda PRIMARY KEY (id_tienda),
    CONSTRAINT fk_tienda_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT uq_tienda_usuario UNIQUE (id_usuario),
    CONSTRAINT uq_tienda_nombre UNIQUE (nombre),
    CONSTRAINT chk_tienda_nombre CHECK (CHAR_LENGTH(BTRIM(nombre)) >= 2),
    CONSTRAINT chk_tienda_responsable CHECK (CHAR_LENGTH(BTRIM(responsable)) >= 2),
    CONSTRAINT chk_tienda_direccion CHECK (CHAR_LENGTH(BTRIM(direccion)) >= 5)
);

CREATE INDEX idx_tienda_estado ON public.tienda(estado);

-- ============================================================
-- 7. INVENTARIO
-- ============================================================

CREATE TABLE public.inventario (
    id_inventario        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_producto          BIGINT NOT NULL,
    id_sucursal          BIGINT NOT NULL,
    stock_actual         BIGINT NOT NULL DEFAULT 0,
    fecha_actualizacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_inventario PRIMARY KEY (id_inventario),
    CONSTRAINT fk_inventario_producto
        FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inventario_sucursal
        FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    -- Un producto solo puede tener un registro por sucursal.
    CONSTRAINT uq_inventario_producto_sucursal UNIQUE (id_producto, id_sucursal),
    CONSTRAINT chk_inventario_stock CHECK (stock_actual >= 0)
);

CREATE INDEX idx_inventario_sucursal ON public.inventario(id_sucursal);

-- Emula el comportamiento de MySQL (ON UPDATE CURRENT_TIMESTAMP):
CREATE OR REPLACE FUNCTION public.set_fecha_actualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_actualizacion := NOW();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_inventario_fecha_actualizacion
    BEFORE UPDATE ON public.inventario
    FOR EACH ROW
    EXECUTE FUNCTION public.set_fecha_actualizacion();

-- ============================================================
-- 8. MOVIMIENTO_INVENTARIO
-- ============================================================

CREATE TABLE public.movimiento_inventario (
    id_movimiento      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_producto        BIGINT NOT NULL,
    id_sucursal        BIGINT NOT NULL,
    id_usuario         BIGINT NOT NULL,
    tipo               VARCHAR(10) NOT NULL,
    cantidad           BIGINT NOT NULL,
    stock_anterior     BIGINT NOT NULL DEFAULT 0,
    stock_resultante   BIGINT NOT NULL,
    motivo             VARCHAR(255),
    fecha_movimiento   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_movimiento_inventario PRIMARY KEY (id_movimiento),
    CONSTRAINT fk_movimiento_producto
        FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_sucursal
        FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_movimiento_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_movimiento_tipo CHECK (tipo IN ('ENTRADA', 'SALIDA', 'AJUSTE')),
    CONSTRAINT chk_movimiento_cantidad CHECK (
        (tipo = 'ENTRADA' AND cantidad >= 0)
        OR (tipo = 'SALIDA' AND cantidad < 0)
        OR (tipo = 'AJUSTE')
    ),
    CONSTRAINT chk_movimiento_stock_resultante CHECK (stock_resultante >= 0)
);

CREATE INDEX idx_movimiento_producto ON public.movimiento_inventario(id_producto);
CREATE INDEX idx_movimiento_sucursal ON public.movimiento_inventario(id_sucursal);
CREATE INDEX idx_movimiento_usuario ON public.movimiento_inventario(id_usuario);
CREATE INDEX idx_movimiento_fecha ON public.movimiento_inventario(fecha_movimiento);

-- ============================================================
-- 9. ALERTA_STOCK
-- ============================================================

CREATE TABLE public.alerta_stock (
    id_alerta          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_inventario      BIGINT NOT NULL,
    fecha_generacion   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado             VARCHAR(10) NOT NULL DEFAULT 'PENDIENTE',

    CONSTRAINT pk_alerta_stock PRIMARY KEY (id_alerta),
    CONSTRAINT fk_alerta_inventario
        FOREIGN KEY (id_inventario) REFERENCES public.inventario(id_inventario)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT chk_alerta_estado CHECK (estado IN ('PENDIENTE', 'ATENDIDA'))
);

-- ============================================================
-- 10. VENTA
-- ============================================================

CREATE TABLE public.venta (
    id_venta       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente     BIGINT,
    id_usuario     BIGINT NOT NULL,
    id_sucursal    BIGINT NOT NULL,
    fecha_venta    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    total          NUMERIC(10,2) NOT NULL DEFAULT 0.00,

    CONSTRAINT pk_venta PRIMARY KEY (id_venta),
    CONSTRAINT fk_venta_cliente
        FOREIGN KEY (id_cliente) REFERENCES public.cliente(id_cliente)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_venta_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_venta_sucursal
        FOREIGN KEY (id_sucursal) REFERENCES public.sucursal(id_sucursal)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_venta_total CHECK (total >= 0)
);

CREATE INDEX idx_venta_cliente ON public.venta(id_cliente);
CREATE INDEX idx_venta_usuario ON public.venta(id_usuario);
CREATE INDEX idx_venta_sucursal ON public.venta(id_sucursal);
CREATE INDEX idx_venta_fecha ON public.venta(fecha_venta);

-- ============================================================
-- 11. DETALLE_VENTA
-- ============================================================

CREATE TABLE public.detalle_venta (
    id_detalle_venta   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_venta           BIGINT NOT NULL,
    id_producto        BIGINT NOT NULL,
    cantidad           BIGINT NOT NULL,
    precio_unitario    NUMERIC(10,2) NOT NULL,
    subtotal           NUMERIC(10,2) NOT NULL,

    CONSTRAINT pk_detalle_venta PRIMARY KEY (id_detalle_venta),
    CONSTRAINT fk_detalle_venta_venta
        FOREIGN KEY (id_venta) REFERENCES public.venta(id_venta)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_detalle_venta_producto
        FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_detalle_venta_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_venta_precio CHECK (precio_unitario > 0),
    CONSTRAINT chk_detalle_venta_subtotal CHECK (subtotal >= 0)
);

CREATE INDEX idx_detalle_venta_venta ON public.detalle_venta(id_venta);
CREATE INDEX idx_detalle_venta_producto ON public.detalle_venta(id_producto);

-- ============================================================
-- 12. PEDIDO
-- ============================================================

CREATE TABLE public.pedido (
    id_pedido      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_tienda      BIGINT NOT NULL,
    id_usuario     BIGINT,
    fecha_pedido   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estado         VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    total          NUMERIC(10,2) NOT NULL DEFAULT 0.00,

    CONSTRAINT pk_pedido PRIMARY KEY (id_pedido),
    CONSTRAINT fk_pedido_tienda
        FOREIGN KEY (id_tienda) REFERENCES public.tienda(id_tienda)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_pedido_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_pedido_total CHECK (total >= 0),
    CONSTRAINT chk_pedido_estado CHECK (estado IN (
        'PENDIENTE', 'CONFIRMADO', 'PREPARANDO', 'LISTO', 'ENTREGADO', 'CANCELADO'
    ))
);

CREATE INDEX idx_pedido_tienda ON public.pedido(id_tienda);
CREATE INDEX idx_pedido_usuario ON public.pedido(id_usuario);
CREATE INDEX idx_pedido_estado ON public.pedido(estado);
CREATE INDEX idx_pedido_fecha ON public.pedido(fecha_pedido);

-- ============================================================
-- 13. DETALLE_PEDIDO
-- ============================================================

CREATE TABLE public.detalle_pedido (
    id_detalle_pedido   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_pedido           BIGINT NOT NULL,
    id_producto         BIGINT NOT NULL,
    cantidad            BIGINT NOT NULL,
    precio_unitario     NUMERIC(10,2) NOT NULL,
    subtotal            NUMERIC(10,2) NOT NULL,

    CONSTRAINT pk_detalle_pedido PRIMARY KEY (id_detalle_pedido),
    CONSTRAINT fk_detalle_pedido_pedido
        FOREIGN KEY (id_pedido) REFERENCES public.pedido(id_pedido)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_detalle_pedido_producto
        FOREIGN KEY (id_producto) REFERENCES public.producto(id_producto)
        ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_detalle_pedido_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_pedido_precio CHECK (precio_unitario > 0),
    CONSTRAINT chk_detalle_pedido_subtotal CHECK (subtotal >= 0)
);

CREATE INDEX idx_detalle_pedido_pedido ON public.detalle_pedido(id_pedido);
CREATE INDEX idx_detalle_pedido_producto ON public.detalle_pedido(id_producto);

-- ============================================================
-- 14. HISTORIAL_PEDIDO
-- ============================================================

CREATE TABLE public.historial_pedido (
    id_historial      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_pedido         BIGINT NOT NULL,
    id_usuario        BIGINT NOT NULL,
    estado_anterior   VARCHAR(50) NOT NULL,
    estado_nuevo      VARCHAR(50) NOT NULL,
    fecha_cambio      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_historial_pedido PRIMARY KEY (id_historial),
    CONSTRAINT fk_historial_pedido
        FOREIGN KEY (id_pedido) REFERENCES public.pedido(id_pedido)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_historial_usuario
        FOREIGN KEY (id_usuario) REFERENCES public.usuario(id_usuario)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX idx_historial_pedido ON public.historial_pedido(id_pedido);
CREATE INDEX idx_historial_fecha ON public.historial_pedido(fecha_cambio);


-- ============================================================
-- VISTAS (consultas con joins / agregaciones para supabase-js)
-- ============================================================

CREATE OR REPLACE VIEW public.vista_productos AS
SELECT p.id_producto, p.id_categoria, p.nombre, p.descripcion, p.precio,
       p.stock_minimo, p.imagen, p.estado, p.estado AS producto_estado,
       c.nombre AS categoria_nombre,
       c.estado AS categoria_estado
FROM public.producto p
INNER JOIN public.categoria c ON c.id_categoria = p.id_categoria;

CREATE OR REPLACE VIEW public.vista_productos_activos AS
SELECT p.id_producto, p.id_categoria, p.nombre, p.descripcion, p.precio,
       p.stock_minimo, p.imagen,
       c.nombre AS categoria_nombre
FROM public.producto p
INNER JOIN public.categoria c ON c.id_categoria = p.id_categoria
WHERE p.estado = TRUE AND c.estado = TRUE;

CREATE OR REPLACE VIEW public.vista_stock_producto AS
SELECT p.id_producto, p.id_categoria, p.nombre, p.descripcion, p.precio,
       p.stock_minimo, p.imagen, p.estado,
       c.nombre AS categoria_nombre,
       COALESCE(SUM(i.stock_actual), 0) AS stock_actual,
       (COALESCE(SUM(i.stock_actual), 0) < p.stock_minimo) AS bajo_stock
FROM public.producto p
INNER JOIN public.categoria c ON c.id_categoria = p.id_categoria
LEFT JOIN public.inventario i ON i.id_producto = p.id_producto
GROUP BY p.id_producto, p.id_categoria, p.nombre, p.descripcion, p.precio,
         p.stock_minimo, p.imagen, p.estado, c.nombre;

CREATE OR REPLACE VIEW public.vista_catalogo_productos AS
SELECT p.id_producto, p.id_categoria, p.nombre, p.descripcion, p.precio,
       p.stock_minimo, p.imagen,
       c.nombre AS categoria_nombre,
       COALESCE(SUM(i.stock_actual), 0) AS stock_disponible
FROM public.producto p
INNER JOIN public.categoria c ON c.id_categoria = p.id_categoria
LEFT JOIN public.inventario i ON i.id_producto = p.id_producto
WHERE p.estado = TRUE AND c.estado = TRUE
GROUP BY p.id_producto, p.id_categoria, p.nombre, p.descripcion, p.precio,
         p.stock_minimo, p.imagen, c.nombre;

CREATE OR REPLACE VIEW public.vista_ventas AS
SELECT v.id_venta, v.id_cliente, v.id_usuario, v.id_sucursal, v.fecha_venta, v.total,
       CONCAT_WS(' ', u.nombre, u.apellido) AS usuario,
       s.nombre AS sucursal,
       CONCAT_WS(' ', c.nombres, c.apellidos) AS cliente
FROM public.venta v
INNER JOIN public.usuario u ON u.id_usuario = v.id_usuario
INNER JOIN public.sucursal s ON s.id_sucursal = v.id_sucursal
LEFT JOIN public.cliente c ON c.id_cliente = v.id_cliente;

CREATE OR REPLACE VIEW public.vista_pedidos AS
SELECT o.id_pedido, o.id_tienda, o.id_usuario, o.fecha_pedido, o.estado, o.total,
       t.nombre AS tienda
FROM public.pedido o
INNER JOIN public.tienda t ON t.id_tienda = o.id_tienda;

CREATE OR REPLACE VIEW public.vista_historial_pedido AS
SELECT h.id_historial, h.id_pedido, h.id_usuario, h.estado_anterior,
       h.estado_nuevo, h.fecha_cambio,
       CONCAT_WS(' ', u.nombre, u.apellido) AS usuario
FROM public.historial_pedido h
INNER JOIN public.usuario u ON u.id_usuario = h.id_usuario;

CREATE OR REPLACE VIEW public.vista_movimientos AS
SELECT m.id_movimiento, m.id_producto, m.id_sucursal, m.id_usuario, m.tipo,
       m.cantidad, m.stock_anterior, m.stock_resultante, m.motivo,
       m.fecha_movimiento,
       p.nombre AS producto,
       s.nombre AS sucursal,
       CONCAT_WS(' ', u.nombre, u.apellido) AS usuario
FROM public.movimiento_inventario m
INNER JOIN public.producto p ON p.id_producto = m.id_producto
INNER JOIN public.sucursal s ON s.id_sucursal = m.id_sucursal
INNER JOIN public.usuario u ON u.id_usuario = m.id_usuario;

CREATE OR REPLACE VIEW public.vista_alertas AS
SELECT a.id_alerta, a.id_inventario, a.fecha_generacion, a.estado,
       p.nombre AS producto, p.stock_minimo, i.stock_actual,
       s.nombre AS sucursal,
       CASE a.estado WHEN 'PENDIENTE' THEN 1 WHEN 'ATENDIDA' THEN 2 END AS estado_orden
FROM public.alerta_stock a
INNER JOIN public.inventario i ON i.id_inventario = a.id_inventario
INNER JOIN public.producto p ON p.id_producto = i.id_producto
INNER JOIN public.sucursal s ON s.id_sucursal = i.id_sucursal;


-- ============================================================
-- FUNCIONES (RPC): operaciones atomicas
-- ============================================================

-- Genera alertas de stock bajo (INSERT...SELECT sin duplicar PENDIENTES)
CREATE OR REPLACE FUNCTION public.generar_alertas_stock()
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_count BIGINT := 0;
BEGIN
    WITH nuevas AS (
        INSERT INTO public.alerta_stock (id_inventario)
        SELECT i.id_inventario
        FROM public.inventario i
        INNER JOIN public.producto p ON p.id_producto = i.id_producto
        WHERE i.stock_actual <= p.stock_minimo
          AND p.estado = TRUE
          AND NOT EXISTS (
              SELECT 1 FROM public.alerta_stock a
              WHERE a.id_inventario = i.id_inventario
                AND a.estado = 'PENDIENTE'
          )
        RETURNING 1
    )
    SELECT COUNT(*) INTO v_count FROM nuevas;

    RETURN v_count;
END;
$$;

-- Registro de venta: venta + detalle + descuento de stock (transaccion)
CREATE OR REPLACE FUNCTION public.registrar_venta(
    p_id_cliente BIGINT,
    p_id_usuario BIGINT,
    p_id_sucursal BIGINT,
    p_total NUMERIC,
    p_detalles JSONB DEFAULT '[]'
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_venta_id     BIGINT;
    v_detalle      JSONB;
    v_id_producto  BIGINT;
    v_cantidad     BIGINT;
    v_stock        BIGINT;
    v_afectados    BIGINT;
BEGIN
    INSERT INTO public.venta (id_cliente, id_usuario, id_sucursal, total)
    VALUES (p_id_cliente, p_id_usuario, p_id_sucursal, p_total)
    RETURNING id_venta INTO v_venta_id;

    FOR v_detalle IN
        SELECT * FROM jsonb_array_elements(COALESCE(p_detalles, '[]'::jsonb))
    LOOP
        v_id_producto := (v_detalle->>'id_producto')::BIGINT;
        v_cantidad    := (v_detalle->>'cantidad')::BIGINT;

        INSERT INTO public.detalle_venta
            (id_venta, id_producto, cantidad, precio_unitario, subtotal)
        VALUES (
            v_venta_id,
            v_id_producto,
            v_cantidad,
            (v_detalle->>'precio_unitario')::NUMERIC(10,2),
            (v_detalle->>'subtotal')::NUMERIC(10,2)
        );

        UPDATE public.inventario
           SET stock_actual = stock_actual - v_cantidad
         WHERE id_producto = v_id_producto
           AND id_sucursal = p_id_sucursal
         RETURNING stock_actual INTO v_stock;

        GET DIAGNOSTICS v_afectados = ROW_COUNT;

        IF v_afectados = 0 THEN
            RAISE EXCEPTION 'Stock insuficiente: el producto % no tiene inventario en la sucursal', v_id_producto;
        END IF;

        IF v_stock < 0 THEN
            RAISE EXCEPTION 'Stock insuficiente para el producto %', v_id_producto;
        END IF;
    END LOOP;

    RETURN v_venta_id;
END;
$$;

-- Registro de pedido: pedido + detalle + historial PENDIENTE (transaccion)
CREATE OR REPLACE FUNCTION public.registrar_pedido(
    p_id_tienda BIGINT,
    p_id_usuario BIGINT,
    p_total NUMERIC,
    p_detalles JSONB DEFAULT '[]'
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_pedido_id BIGINT;
    v_detalle   JSONB;
BEGIN
    INSERT INTO public.pedido (id_tienda, id_usuario, total)
    VALUES (p_id_tienda, p_id_usuario, p_total)
    RETURNING id_pedido INTO v_pedido_id;

    FOR v_detalle IN
        SELECT * FROM jsonb_array_elements(COALESCE(p_detalles, '[]'::jsonb))
    LOOP
        INSERT INTO public.detalle_pedido
            (id_pedido, id_producto, cantidad, precio_unitario, subtotal)
        VALUES (
            v_pedido_id,
            (v_detalle->>'id_producto')::BIGINT,
            (v_detalle->>'cantidad')::BIGINT,
            (v_detalle->>'precio_unitario')::NUMERIC(10,2),
            (v_detalle->>'subtotal')::NUMERIC(10,2)
        );
    END LOOP;

    INSERT INTO public.historial_pedido
        (id_pedido, id_usuario, estado_anterior, estado_nuevo)
    VALUES (v_pedido_id, p_id_usuario, 'NUEVO', 'PENDIENTE');

    RETURN v_pedido_id;
END;
$$;

-- Actualiza el estado de un pedido y registra el historial (transaccion)
CREATE OR REPLACE FUNCTION public.actualizar_estado_pedido(
    p_id_pedido BIGINT,
    p_id_usuario BIGINT,
    p_estado_anterior VARCHAR,
    p_estado_nuevo VARCHAR
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    UPDATE public.pedido SET estado = p_estado_nuevo WHERE id_pedido = p_id_pedido;

    INSERT INTO public.historial_pedido
        (id_pedido, id_usuario, estado_anterior, estado_nuevo)
    VALUES (p_id_pedido, p_id_usuario, p_estado_anterior, p_estado_nuevo);
END;
$$;

-- Registra un movimiento de inventario y actualiza stock (transaccion)
CREATE OR REPLACE FUNCTION public.registrar_movimiento_inventario(
    p_id_producto BIGINT,
    p_id_sucursal BIGINT,
    p_id_usuario BIGINT,
    p_tipo VARCHAR,
    p_cantidad BIGINT,
    p_motivo VARCHAR DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_inventario      RECORD;
    v_stock_anterior  BIGINT;
    v_stock_resultante BIGINT;
    v_movimiento_id   BIGINT;
BEGIN
    SELECT * INTO v_inventario
    FROM public.inventario
    WHERE id_producto = p_id_producto AND id_sucursal = p_id_sucursal
    FOR UPDATE;

    v_stock_anterior := COALESCE(v_inventario.stock_actual, 0);

    IF p_tipo = 'ENTRADA' THEN
        v_stock_resultante := v_stock_anterior + p_cantidad;
    ELSIF p_tipo = 'SALIDA' THEN
        IF p_cantidad > v_stock_anterior THEN
            RAISE EXCEPTION 'Stock insuficiente. Disponible: %', v_stock_anterior;
        END IF;
        v_stock_resultante := v_stock_anterior - p_cantidad;
    ELSE
        IF p_motivo IS NULL OR CHAR_LENGTH(BTRIM(p_motivo)) < 2 THEN
            RAISE EXCEPTION 'Debe indicar el motivo del ajuste.';
        END IF;
        v_stock_resultante := p_cantidad;
    END IF;

    IF FOUND THEN
        UPDATE public.inventario
           SET stock_actual = v_stock_resultante
         WHERE id_inventario = v_inventario.id_inventario;
    ELSE
        INSERT INTO public.inventario (id_producto, id_sucursal, stock_actual)
        VALUES (p_id_producto, p_id_sucursal, v_stock_resultante);
    END IF;

    INSERT INTO public.movimiento_inventario
        (id_producto, id_sucursal, id_usuario, tipo, cantidad,
         stock_anterior, stock_resultante, motivo)
    VALUES (
        p_id_producto, p_id_sucursal, p_id_usuario, p_tipo,
        CASE WHEN p_tipo = 'SALIDA' THEN -p_cantidad ELSE p_cantidad END,
        v_stock_anterior, v_stock_resultante,
        p_motivo
    )
    RETURNING id_movimiento INTO v_movimiento_id;

    RETURN v_movimiento_id;
END;
$$;

-- Ajusta el stock total de un producto repartiendolo entre sucursales (transaccion)
-- p_distribucion: [{ id_inventario, id_sucursal, stock_anterior, nuevo_stock, cantidad }]
CREATE OR REPLACE FUNCTION public.ajustar_stock_total(
    p_id_producto BIGINT,
    p_id_usuario BIGINT,
    p_motivo VARCHAR,
    p_distribucion JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_item  JSONB;
    v_id_inventario BIGINT;
BEGIN
    FOR v_item IN
        SELECT * FROM jsonb_array_elements(COALESCE(p_distribucion, '[]'::jsonb))
    LOOP
        v_id_inventario := (v_item->>'id_inventario')::BIGINT;

        IF v_id_inventario IS NULL THEN
            INSERT INTO public.inventario (id_producto, id_sucursal, stock_actual)
            VALUES (p_id_producto, (v_item->>'id_sucursal')::BIGINT, (v_item->>'nuevo_stock')::BIGINT)
            RETURNING id_inventario INTO v_id_inventario;
        ELSE
            UPDATE public.inventario
               SET stock_actual = (v_item->>'nuevo_stock')::BIGINT
             WHERE id_inventario = v_id_inventario;
        END IF;

        INSERT INTO public.movimiento_inventario
            (id_producto, id_sucursal, id_usuario, tipo, cantidad,
             stock_anterior, stock_resultante, motivo)
        VALUES (
            p_id_producto,
            (v_item->>'id_sucursal')::BIGINT,
            p_id_usuario,
            'AJUSTE',
            (v_item->>'cantidad')::BIGINT,
            (v_item->>'stock_anterior')::BIGINT,
            (v_item->>'nuevo_stock')::BIGINT,
            p_motivo
        );
    END LOOP;
END;
$$;


-- ============================================================
-- FUNCIONES (RPC): reportes y dashboard
-- ============================================================

CREATE OR REPLACE FUNCTION public.reporte_ventas_resumen(
    p_fecha_desde TEXT DEFAULT NULL,
    p_fecha_hasta TEXT DEFAULT NULL,
    p_id_sucursal BIGINT DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_desde     TIMESTAMPTZ;
    v_hasta     TIMESTAMPTZ;
    v_totales   JSON;
    v_por_sucursal JSON;
    v_por_producto  JSON;
    v_por_dia       JSON;
BEGIN
    IF p_fecha_desde IS NOT NULL AND p_fecha_desde <> '' THEN
        v_desde := (p_fecha_desde || ' 00:00:00')::TIMESTAMPTZ;
    END IF;
    IF p_fecha_hasta IS NOT NULL AND p_fecha_hasta <> '' THEN
        v_hasta := (p_fecha_hasta || ' 23:59:59')::TIMESTAMPTZ;
    END IF;

    SELECT json_build_object(
               'total_ventas', COUNT(*),
               'total_ingresos', ROUND(COALESCE(SUM(v.total), 0)::NUMERIC, 2)
           )
      INTO v_totales
      FROM public.venta v
     WHERE (v_desde IS NULL OR v.fecha_venta >= v_desde)
       AND (v_hasta IS NULL OR v.fecha_venta <= v_hasta)
       AND (p_id_sucursal IS NULL OR v.id_sucursal = p_id_sucursal);

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_por_sucursal
      FROM (
          SELECT s.nombre AS name, COUNT(*) AS value
          FROM public.venta v
          INNER JOIN public.sucursal s ON s.id_sucursal = v.id_sucursal
          WHERE (v_desde IS NULL OR v.fecha_venta >= v_desde)
            AND (v_hasta IS NULL OR v.fecha_venta <= v_hasta)
            AND (p_id_sucursal IS NULL OR v.id_sucursal = p_id_sucursal)
          GROUP BY s.id_sucursal, s.nombre
      ) t;

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_por_producto
      FROM (
          SELECT p.nombre AS name, SUM(dv.cantidad) AS value
          FROM public.detalle_venta dv
          INNER JOIN public.venta v ON v.id_venta = dv.id_venta
          INNER JOIN public.producto p ON p.id_producto = dv.id_producto
          WHERE (v_desde IS NULL OR v.fecha_venta >= v_desde)
            AND (v_hasta IS NULL OR v.fecha_venta <= v_hasta)
            AND (p_id_sucursal IS NULL OR v.id_sucursal = p_id_sucursal)
          GROUP BY p.id_producto, p.nombre
          ORDER BY value DESC
          LIMIT 10
      ) t;

    SELECT COALESCE(json_agg(json_build_object('date', t.date, 'total', t.total) ORDER BY t.date), '[]'::json)
      INTO v_por_dia
      FROM (
          SELECT (v.fecha_venta::date)::text AS date,
                 ROUND(COALESCE(SUM(v.total), 0)::NUMERIC, 2) AS total
          FROM public.venta v
          WHERE (v_desde IS NULL OR v.fecha_venta >= v_desde)
            AND (v_hasta IS NULL OR v.fecha_venta <= v_hasta)
            AND (p_id_sucursal IS NULL OR v.id_sucursal = p_id_sucursal)
          GROUP BY v.fecha_venta::date
      ) t;

    RETURN json_build_object(
        'totals', v_totales,
        'byBranch', v_por_sucursal,
        'byProduct', v_por_producto,
        'byDay', v_por_dia
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.reporte_pedidos_resumen(
    p_fecha_desde TEXT DEFAULT NULL,
    p_fecha_hasta TEXT DEFAULT NULL,
    p_estado TEXT DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_desde   TIMESTAMPTZ;
    v_hasta   TIMESTAMPTZ;
    v_totales JSON;
    v_por_estado JSON;
    v_por_tienda JSON;
BEGIN
    IF p_fecha_desde IS NOT NULL AND p_fecha_desde <> '' THEN
        v_desde := (p_fecha_desde || ' 00:00:00')::TIMESTAMPTZ;
    END IF;
    IF p_fecha_hasta IS NOT NULL AND p_fecha_hasta <> '' THEN
        v_hasta := (p_fecha_hasta || ' 23:59:59')::TIMESTAMPTZ;
    END IF;

    SELECT json_build_object(
               'total_pedidos', COUNT(*),
               'total_pedidos_monto', ROUND(COALESCE(SUM(o.total), 0)::NUMERIC, 2)
           )
      INTO v_totales
      FROM public.pedido o
     WHERE (v_desde IS NULL OR o.fecha_pedido >= v_desde)
       AND (v_hasta IS NULL OR o.fecha_pedido <= v_hasta)
       AND (p_estado IS NULL OR o.estado = p_estado);

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_por_estado
      FROM (
          SELECT o.estado AS name, COUNT(*) AS value
          FROM public.pedido o
          WHERE (v_desde IS NULL OR o.fecha_pedido >= v_desde)
            AND (v_hasta IS NULL OR o.fecha_pedido <= v_hasta)
            AND (p_estado IS NULL OR o.estado = p_estado)
          GROUP BY o.estado
      ) t;

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_por_tienda
      FROM (
          SELECT t.nombre AS name, COUNT(*) AS value
          FROM public.pedido o
          INNER JOIN public.tienda t ON t.id_tienda = o.id_tienda
          WHERE (v_desde IS NULL OR o.fecha_pedido >= v_desde)
            AND (v_hasta IS NULL OR o.fecha_pedido <= v_hasta)
            AND (p_estado IS NULL OR o.estado = p_estado)
          GROUP BY t.id_tienda, t.nombre
          ORDER BY value DESC
          LIMIT 10
      ) t;

    RETURN json_build_object(
        'totals', v_totales,
        'byEstado', v_por_estado,
        'byTienda', v_por_tienda
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.reporte_productos_resumen()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_totales   JSON;
    v_por_categoria JSON;
    v_low_stock JSON;
BEGIN
    SELECT json_build_object(
               'total_productos', COUNT(*),
               'productos_activos', COUNT(*) FILTER (WHERE p.estado),
               'productos_inactivos', COUNT(*) FILTER (WHERE NOT p.estado)
           )
      INTO v_totales
      FROM public.producto p;

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_por_categoria
      FROM (
          SELECT c.nombre AS name, COUNT(p.id_producto) AS value
          FROM public.categoria c
          LEFT JOIN public.producto p ON p.id_categoria = c.id_categoria
          GROUP BY c.id_categoria, c.nombre
      ) t;

    SELECT COALESCE(json_agg(json_build_object(
               'id_producto', t.id_producto,
               'nombre', t.nombre,
               'precio', t.precio,
               'stock_minimo', t.stock_minimo,
               'stock_total', t.stock_total
           ) ORDER BY t.stock_total, t.nombre), '[]'::json)
      INTO v_low_stock
      FROM (
          SELECT p.id_producto, p.nombre, ROUND(p.precio::NUMERIC, 2) AS precio,
                 p.stock_minimo,
                 COALESCE(SUM(i.stock_actual), 0) AS stock_total
          FROM public.producto p
          LEFT JOIN public.inventario i ON i.id_producto = p.id_producto
          WHERE p.estado = TRUE
          GROUP BY p.id_producto, p.nombre, p.precio, p.stock_minimo
          HAVING COALESCE(SUM(i.stock_actual), 0) < p.stock_minimo
      ) t;

    RETURN json_build_object('totals', v_totales, 'byCategory', v_por_categoria, 'lowStock', v_low_stock);
END;
$$;

CREATE OR REPLACE FUNCTION public.reporte_inventario_resumen(
    p_fecha_desde TEXT DEFAULT NULL,
    p_fecha_hasta TEXT DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_desde  TIMESTAMPTZ;
    v_hasta  TIMESTAMPTZ;
    v_totales JSON;
    v_por_tipo  JSON;
    v_stock     JSON;
BEGIN
    IF p_fecha_desde IS NOT NULL AND p_fecha_desde <> '' THEN
        v_desde := (p_fecha_desde || ' 00:00:00')::TIMESTAMPTZ;
    END IF;
    IF p_fecha_hasta IS NOT NULL AND p_fecha_hasta <> '' THEN
        v_hasta := (p_fecha_hasta || ' 23:59:59')::TIMESTAMPTZ;
    END IF;

    SELECT json_build_object(
               'total_movimientos', COUNT(*),
               'entradas', COUNT(*) FILTER (WHERE m.tipo = 'ENTRADA'),
               'salidas',  COUNT(*) FILTER (WHERE m.tipo = 'SALIDA'),
               'ajustes',  COUNT(*) FILTER (WHERE m.tipo = 'AJUSTE')
           )
      INTO v_totales
      FROM public.movimiento_inventario m
     WHERE (v_desde IS NULL OR m.fecha_movimiento >= v_desde)
       AND (v_hasta IS NULL OR m.fecha_movimiento <= v_hasta);

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_por_tipo
      FROM (
          SELECT m.tipo AS name, COUNT(*) AS value
          FROM public.movimiento_inventario m
          WHERE (v_desde IS NULL OR m.fecha_movimiento >= v_desde)
            AND (v_hasta IS NULL OR m.fecha_movimiento <= v_hasta)
          GROUP BY m.tipo
      ) t;

    SELECT json_build_object(
               'productos_con_stock', (SELECT COUNT(DISTINCT p.id_producto)
                                         FROM public.producto p
                                         LEFT JOIN public.inventario i ON i.id_producto = p.id_producto
                                        WHERE p.estado = TRUE),
               'unidades_totales', (SELECT COALESCE(SUM(i.stock_actual), 0)
                                      FROM public.inventario i)
           )
      INTO v_stock;

    RETURN json_build_object('totals', v_totales, 'byTipo', v_por_tipo, 'stock', v_stock);
END;
$$;

CREATE OR REPLACE FUNCTION public.reporte_dashboard()
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    v_kpis JSON;
    v_ventas_por_sucursal JSON;
    v_pedidos_por_estado  JSON;
    v_productos_por_categoria JSON;
    v_low_stock JSON;
BEGIN
    SELECT json_build_object(
               'total_ventas', (SELECT COUNT(*) FROM public.venta),
               'total_ingresos', ROUND((SELECT COALESCE(SUM(total), 0) FROM public.venta)::NUMERIC, 2),
               'total_pedidos', (SELECT COUNT(*) FROM public.pedido),
               'total_pedidos_monto', ROUND((SELECT COALESCE(SUM(total), 0) FROM public.pedido)::NUMERIC, 2),
               'total_productos', (SELECT COUNT(*) FROM public.producto WHERE estado = TRUE),
               'total_bajo_stock', (SELECT COUNT(*) FROM public.producto p
                                     WHERE p.estado = TRUE
                                       AND (SELECT COALESCE(SUM(i.stock_actual), 0)
                                              FROM public.inventario i
                                             WHERE i.id_producto = p.id_producto) < p.stock_minimo),
               'unidades_totales', (SELECT COALESCE(SUM(stock_actual), 0) FROM public.inventario),
               'total_sucursales', (SELECT COUNT(*) FROM public.sucursal WHERE estado = TRUE),
               'total_clientes', (SELECT COUNT(*) FROM public.cliente),
               'total_tiendas', (SELECT COUNT(*) FROM public.tienda WHERE estado = TRUE)
           )
      INTO v_kpis;

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_ventas_por_sucursal
      FROM (
          SELECT s.nombre AS name, COUNT(*) AS value
          FROM public.venta v
          INNER JOIN public.sucursal s ON s.id_sucursal = v.id_sucursal
          GROUP BY s.id_sucursal, s.nombre
      ) t;

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_pedidos_por_estado
      FROM (
          SELECT estado AS name, COUNT(*) AS value
          FROM public.pedido
          GROUP BY estado
      ) t;

    SELECT COALESCE(json_agg(json_build_object('name', t.name, 'value', t.value) ORDER BY t.value DESC), '[]'::json)
      INTO v_productos_por_categoria
      FROM (
          SELECT c.nombre AS name, COUNT(p.id_producto) AS value
          FROM public.categoria c
          LEFT JOIN public.producto p ON p.id_categoria = c.id_categoria AND p.estado = TRUE
          GROUP BY c.id_categoria, c.nombre
      ) t;

    SELECT COALESCE(json_agg(json_build_object(
               'name', t.name, 'value', t.value, 'stock_minimo', t.stock_minimo
           ) ORDER BY t.value, t.name), '[]'::json)
      INTO v_low_stock
      FROM (
          SELECT p.nombre AS name, COALESCE(SUM(i.stock_actual), 0) AS value, p.stock_minimo
          FROM public.producto p
          LEFT JOIN public.inventario i ON i.id_producto = p.id_producto
          WHERE p.estado = TRUE
          GROUP BY p.id_producto, p.nombre, p.stock_minimo
          HAVING COALESCE(SUM(i.stock_actual), 0) < p.stock_minimo
          LIMIT 5
      ) t;

    RETURN json_build_object(
        'kpis', v_kpis,
        'charts', json_build_object(
            'salesByBranch', v_ventas_por_sucursal,
            'ordersByEstado', v_pedidos_por_estado,
            'productsByCategory', v_productos_por_categoria,
            'lowStock', v_low_stock
        )
    );
END;
$$;


-- ============================================================
-- DATOS SEMILLA (solo si las tablas estan vacias)
-- Contrasenas: admin123, vendedor123, inventario123, encargado123, encargado2_123
-- ============================================================

INSERT INTO public.usuario (nombre, apellido, correo, password, rol)
SELECT v.nombre, v.apellido, v.correo, v.password, v.rol
FROM (VALUES
    ('Administrador', 'JuampyZel', 'admin@juampyzel.com', '$2a$10$p8HxevdO7f30sXXiDjylFOfO78TSUxNKLudVm3HlJXrgW62DPJHC.', 'ADMINISTRADOR'),
    ('Carlos', 'Vendedor', 'vendedor@juampyzel.com', '$2a$10$PR3NEEc.Z.y1HJJmiJQ/4eyYw0QaIsyUs6dAM7jwCtC23GSfg/13e', 'VENDEDOR'),
    ('Juan', 'Inventario', 'inventario@juampyzel.com', '$2a$10$j1Bg/089VqiguC4RBinM1eJIYrpsO88Oh4RbE.C.reDAouf96VHvu', 'INVENTARIO'),
    ('Lucia', 'Encargada', 'encargado@juampyzel.com', '$2a$10$x5s1Czhd33dbMyNqwCgngeA3V5ICI6SFwyzuuIKvPzRwhqEnoGixC', 'ENCARGADO_SUCURSAL'),
    ('Miguel', 'Encargado', 'encargado2@juampyzel.com', '$2a$10$x5s1Czhd33dbMyNqwCgngeA3V5ICI6SFwyzuuIKvPzRwhqEnoGixC', 'ENCARGADO_SUCURSAL')
) AS v(nombre, apellido, correo, password, rol)
WHERE NOT EXISTS (SELECT 1 FROM public.usuario);

INSERT INTO public.categoria (nombre, descripcion)
SELECT v.nombre, v.descripcion
FROM (VALUES
    ('Helados de crema', 'Helados elaborados a base de crema'),
    ('Helados de fruta', 'Helados elaborados con diferentes frutas'),
    ('Paletas', 'Paletas y helados individuales'),
    ('Especiales', 'Productos especiales de JuampyZel')
) AS v(nombre, descripcion)
WHERE NOT EXISTS (SELECT 1 FROM public.categoria);


-- ============================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================
-- El backend accede con la clave SERVICE ROLE, que ignora RLS.
-- Las politicas restringen el acceso directo (publishable key).
-- No se crean politicas publicas de escritura (USING true).
-- ============================================================

ALTER TABLE public.usuario               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categoria             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.producto              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sucursal              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cliente               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tienda                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventario            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.movimiento_inventario ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerta_stock          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venta                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_venta         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedido                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.detalle_pedido        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historial_pedido      ENABLE ROW LEVEL SECURITY;

-- Lectura publica del catalogo (productos, categorias y sucursales activas).
-- Necesaria para futuras consultas directas del frontend con la publishable key.
CREATE POLICY p_anon_lectura_categorias_activas
    ON public.categoria FOR SELECT TO anon, authenticated
    USING (estado = TRUE);

CREATE POLICY p_anon_lectura_productos_activos
    ON public.producto FOR SELECT TO anon, authenticated
    USING (estado = TRUE);

CREATE POLICY p_anon_lectura_sucursales_activas
    ON public.sucursal FOR SELECT TO anon, authenticated
    USING (estado = TRUE);

-- SSO / Supabase Auth: si en el futuro se integra auth.users, relacionar con:
--   user_id UUID REFERENCES auth.users(id)
-- y agregar politicas por rol mediante auth.uid() / auth.jwt().


-- ============================================================
-- PERMISOS
-- ============================================================

GRANT SELECT ON public.vista_productos TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_productos_activos TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_stock_producto TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_catalogo_productos TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_ventas TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_pedidos TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_historial_pedido TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_movimientos TO anon, authenticated, service_role;
GRANT SELECT ON public.vista_alertas TO anon, authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.generar_alertas_stock() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registrar_venta(BIGINT, BIGINT, BIGINT, NUMERIC, JSONB) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registrar_pedido(BIGINT, BIGINT, NUMERIC, JSONB) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.actualizar_estado_pedido(BIGINT, BIGINT, VARCHAR, VARCHAR) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.registrar_movimiento_inventario(BIGINT, BIGINT, BIGINT, VARCHAR, BIGINT, VARCHAR) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.ajustar_stock_total(BIGINT, BIGINT, VARCHAR, JSONB) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reporte_ventas_resumen(TEXT, TEXT, BIGINT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reporte_pedidos_resumen(TEXT, TEXT, TEXT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reporte_productos_resumen() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reporte_inventario_resumen(TEXT, TEXT) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.reporte_dashboard() TO authenticated, service_role;